import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { auth, signIn, signOut } from "@/auth";
import { Button, Welcome } from "@/app/components";
import Image from "next/image";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Weights Dashboard",
  description: "Generated by create next app",
};

function SignIn() {
  return (
    <form
      action={async () => {
        "use server";
        await signIn("github");
      }}
      className="w-full flex justify-between items-center gap-2"
    >
      <p className="text-sm sm:text-base">You are not logged in</p>
      <Button text="Sign in with GitHub" buttonType="submit" />
    </form>
  );
}

function SignOut({ children }: { children: React.ReactNode }) {
  return (
    <form
      action={async () => {
        "use server";
        await signOut();
      }}
      className="w-full flex justify-between items-center"
    >
      <p className="text-sm sm:text-base">{children}</p>
      <Button text="Sign Out" buttonType="submit" />
    </form>
  );
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let session = await auth();
  let user = session?.user?.name;

  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="w-full p-4 max-w-screen-2xl mx-auto sm:px-10 sm:py-6 text-white">
          <div className="flex gap-2 items-center sm:gap-4">
            <Link href="/">
              <Image
                src="/mor-logo.svg" // Path to the image in the public folder
                alt="mor"
                width={32}
                height={32}
                className="h-8 w-auto"
                priority={true}
              />
            </Link>
            <div className="w-full">
              {user ? <SignOut>{`Welcome, ${user}`}</SignOut> : <SignIn />}
            </div>
          </div>
          <div className="w-full h-px bg-neutral-600 mt-5"></div>
        </header>

        <main className="p-4 max-w-screen-2xl mx-auto sm:px-10 text-white">
          {user && <>{children}</>}
          {!user && <Welcome />}
        </main>
      </body>
    </html>
  );
}
