import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { auth, signIn, signOut } from "@/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Weights Dashboard",
  description: "Generated by create next app",
};

function SignIn() {
  return (
    <form
      action={async () => {
        "use server";
        await signIn("github");
      }}
      className="w-full flex justify-between items-center"
    >
      <p>You are not logged in</p>
      <button type="submit" className="px-3 py-2 border">
        Sign in with GitHub
      </button>
    </form>
  );
}

function SignOut({ children }: { children: React.ReactNode }) {
  return (
    <form
      action={async () => {
        "use server";
        await signOut();
      }}
      className="w-full flex justify-between items-center"
    >
      <p>{children}</p>
      <button type="submit" className="px-3 py-2 border">
        Sign out
      </button>
    </form>
  );
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let session = await auth();
  let user = session?.user?.name;
  console.log(session);

  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="w-full px-4 max-w-screen-2xl mx-auto sm:px-10 sm:py-6">
          <div>
            {user ? <SignOut>{`Welcome, ${user}`}</SignOut> : <SignIn />}
          </div>
          <div className="w-full h-px bg-slate-300 mt-5"></div>
        </header>

        {user && (
          <main className="p-4 max-w-screen-2xl mx-auto sm:px-10">
            {children}
          </main>
        )}
      </body>
    </html>
  );
}
